site_name: HayProgress
site_description: My Eastern Armenian Language Journey
site_url: https://hayprogress.github.io/Hayprogress/

theme:
  name: material
  palette:
    primary: indigo
    accent: blue
  features:
    - navigation.tabs
    - navigation.indexes
    - navigation.top
    - content.code.copy

nav:
  - Home: index.md
  - AVC Eastern Armenian:
      - Overview: avc/index.md
      - Beginner:
          - Overview: avc/beginner/index.md
          - Lesson 1:
              - Overview: avc/beginner/lesson-1/index.md
              - Alphabet: avc/beginner/lesson-1/alphabet.md
              - Grammar: avc/beginner/lesson-1/grammar.md
              - Thematic Words: avc/beginner/lesson-1/thematic-words.md
              - Dialogues: avc/beginner/lesson-1/dialogues.md
              - Vocabulary: avc/beginner/lesson-1/vocabulary.md
              - Song: avc/beginner/lesson-1/song.md
              - Story: avc/beginner/lesson-1/story.md
              - Resources: avc/beginner/lesson-1/resources.md
          - Lesson 2: avc/beginner/lesson-2/index.md
          - Lesson 3: avc/beginner/lesson-3/index.md
          - Lesson 4: avc/beginner/lesson-4/index.md
          - Lesson 5: avc/beginner/lesson-5/index.md
          - Lesson 6: avc/beginner/lesson-6/index.md
          - Lesson 7: avc/beginner/lesson-7/index.md
          - Lesson 8: avc/beginner/lesson-8/index.md
      - Elementary:
          - Overview: avc/elementary/index.md
          - Lesson 1:
              - Overview: avc/elementary/lesson-1/index.md
              - Grammar: avc/elementary/lesson-1/grammar.md
              - Thematic Words: avc/elementary/lesson-1/thematic-words.md
              - Dialogues: avc/elementary/lesson-1/dialogues.md
              - Vocabulary: avc/elementary/lesson-1/vocabulary.md
              - Song: avc/elementary/lesson-1/song.md
              - Story: avc/elementary/lesson-1/story.md
              - Resources: avc/elementary/lesson-1/resources.md
          - Lesson 2: avc/elementary/lesson-2/index.md
          - Lesson 3: avc/elementary/lesson-3/index.md
          - Lesson 4: avc/elementary/lesson-4/index.md
          - Lesson 5: avc/elementary/lesson-5/index.md
          - Lesson 6: avc/elementary/lesson-6/index.md
          - Lesson 7: avc/elementary/lesson-7/index.md
          - Lesson 8: avc/elementary/lesson-8/index.md
      - Pre-Intermediate:
          - Overview: avc/pre-intermediate/index.md
          - Lesson 1: avc/pre-intermediate/lesson-1/index.md
          - Lesson 2: avc/pre-intermediate/lesson-2/index.md
          - Lesson 3: avc/pre-intermediate/lesson-3/index.md
          - Lesson 4: avc/pre-intermediate/lesson-4/index.md
          - Lesson 5: avc/pre-intermediate/lesson-5/index.md
          - Lesson 6: avc/pre-intermediate/lesson-6/index.md
          - Lesson 7: avc/pre-intermediate/lesson-7/index.md
          - Lesson 8: avc/pre-intermediate/lesson-8/index.md
      - Intermediate:
          - Overview: avc/intermediate/index.md
          - Lesson 1: avc/intermediate/lesson-1/index.md
          - Lesson 2: avc/intermediate/lesson-2/index.md
          - Lesson 3: avc/intermediate/lesson-3/index.md
          - Lesson 4: avc/intermediate/lesson-4/index.md
          - Lesson 5: avc/intermediate/lesson-5/index.md
          - Lesson 6: avc/intermediate/lesson-6/index.md
          - Lesson 7: avc/intermediate/lesson-7/index.md
          - Lesson 8: avc/intermediate/lesson-8/index.md
      - Upper Intermediate:
          - Overview: avc/upper-intermediate/index.md
          - Lesson 1: avc/upper-intermediate/lesson-1/index.md
          - Lesson 2: avc/upper-intermediate/lesson-2/index.md
          - Lesson 3: avc/upper-intermediate/lesson-3/index.md
          - Lesson 4: avc/upper-intermediate/lesson-4/index.md
          - Lesson 5: avc/upper-intermediate/lesson-5/index.md
          - Lesson 6: avc/upper-intermediate/lesson-6/index.md
          - Lesson 7: avc/upper-intermediate/lesson-7/index.md
          - Lesson 8: avc/upper-intermediate/lesson-8/index.md
      - Pre-Advanced:
          - Overview: avc/pre-advanced/index.md
          - Lesson 1: avc/pre-advanced/lesson-1/index.md
          - Lesson 2: avc/pre-advanced/lesson-2/index.md
          - Lesson 3: avc/pre-advanced/lesson-3/index.md
          - Lesson 4: avc/pre-advanced/lesson-4/index.md
          - Lesson 5: avc/pre-advanced/lesson-5/index.md
          - Lesson 6: avc/pre-advanced/lesson-6/index.md
          - Lesson 7: avc/pre-advanced/lesson-7/index.md
          - Lesson 8: avc/pre-advanced/lesson-8/index.md
      - Advanced:
          - Overview: avc/advanced/index.md
          - Lesson 1: avc/advanced/lesson-1/index.md
          - Lesson 2: avc/advanced/lesson-2/index.md
          - Lesson 3: avc/advanced/lesson-3/index.md
          - Lesson 4: avc/advanced/lesson-4/index.md
          - Lesson 5: avc/advanced/lesson-5/index.md
          - Lesson 6: avc/advanced/lesson-6/index.md
          - Lesson 7: avc/advanced/lesson-7/index.md
          - Lesson 8: avc/advanced/lesson-8/index.md
      - Proficiency:
          - Overview: avc/proficiency/index.md
          - Lesson 1: avc/proficiency/lesson-1/index.md
          - Lesson 2: avc/proficiency/lesson-2/index.md
          - Lesson 3: avc/proficiency/lesson-3/index.md
          - Lesson 4: avc/proficiency/lesson-4/index.md
          - Lesson 5: avc/proficiency/lesson-5/index.md
          - Lesson 6: avc/proficiency/lesson-6/index.md
          - Lesson 7: avc/proficiency/lesson-7/index.md
          - Lesson 8: avc/proficiency/lesson-8/index.md
      - Superior / Mastery:
          - Overview: avc/superior-mastery/index.md
          - Lesson 1: avc/superior-mastery/lesson-1/index.md
          - Lesson 2: avc/superior-mastery/lesson-2/index.md
          - Lesson 3: avc/superior-mastery/lesson-3/index.md
          - Lesson 4: avc/superior-mastery/lesson-4/index.md
          - Lesson 5: avc/superior-mastery/lesson-5/index.md
          - Lesson 6: avc/superior-mastery/lesson-6/index.md
          - Lesson 7: avc/superior-mastery/lesson-7/index.md
          - Lesson 8: avc/superior-mastery/lesson-8/index.md
      - Conversational Part 1:
          - Overview: avc/conversational-1/index.md
          - Lesson 1: avc/conversational-1/lesson-1/index.md
          - Lesson 2: avc/conversational-1/lesson-2/index.md
          - Lesson 3: avc/conversational-1/lesson-3/index.md
          - Lesson 4: avc/conversational-1/lesson-4/index.md
          - Lesson 5: avc/conversational-1/lesson-5/index.md
          - Lesson 6: avc/conversational-1/lesson-6/index.md
          - Lesson 7: avc/conversational-1/lesson-7/index.md
          - Lesson 8: avc/conversational-1/lesson-8/index.md
      - Conversational Part 2:
          - Overview: avc/conversational-2/index.md
          - Lesson 1: avc/conversational-2/lesson-1/index.md
          - Lesson 2: avc/conversational-2/lesson-2/index.md
          - Lesson 3: avc/conversational-2/lesson-3/index.md
          - Lesson 4: avc/conversational-2/lesson-4/index.md
          - Lesson 5: avc/conversational-2/lesson-5/index.md
          - Lesson 6: avc/conversational-2/lesson-6/index.md
          - Lesson 7: avc/conversational-2/lesson-7/index.md
          - Lesson 8: avc/conversational-2/lesson-8/index.md
  - AYoLingo: ayolingo/index.md
  - Memrise: memrise/index.md
  - Ling: ling/index.md
  - 50 Languages: 50-languages/index.md
  - Pimsleur: pimsleur/index.md

markdown_extensions:
  - pymdownx.superfences
